<?xml version="1.0" encoding="UTF-8"?><testrun name="UsuarioRepository" project="gerenciamento-tarefa" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.melim.gerenciamento_tarefa.repository.UsuarioRepository" time="0.959" displayname="UsuarioRepository" uniqueid="[engine:junit-jupiter]/[class:com.melim.gerenciamento_tarefa.repository.UsuarioRepository]">
    <testcase name="deveSalvarUmUsuario" classname="com.melim.gerenciamento_tarefa.repository.UsuarioRepository" time="0.959" displayname="deveSalvarUmUsuario()" uniqueid="[engine:junit-jupiter]/[class:com.melim.gerenciamento_tarefa.repository.UsuarioRepository]/[method:deveSalvarUmUsuario()]">
      <failure>
        <expected>null</expected>
        <actual>1</actual>
        org.opentest4j.AssertionFailedError: &#13;
expected: null&#13;
 but was: 1&#13;
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)&#13;
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)&#13;
	at com.melim.gerenciamento_tarefa.repository.UsuarioRepository.deveSalvarUmUsuario(UsuarioRepository.java:32)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
